### PR TITLE
Added link to a 3d-printed case to README

### LINKED ISSUE #1: Case for avr-tqfp-programmer
I made a programmer based on your project, thank you for creating this programmer. I made a simple case for this and are free for you to add to project if you wish.

https://www.thingiverse.com/thing:4529554

### PR DESCRIPTION
**Pull request by datamann**

### CODE REVIEW

**Comment by datamann** [comment]
Added link to a 3d-printed case to README

**Comment by hazarkarabay** [comment]
Thanks but the Thingiverse link seems to be broken (404). Can you check it (maybe it is set to private - try with a private/incognito window) ? 
I'll merge when its corrected.

**Comment by datamann** [comment]
@hazarkarabay Could you please try the URL now? I forgot to press the "Publish" button in Thingiverse...

**Comment by datamann** [comment]
@hazarkarabay If you want to add the files in here and not reference a link you are free to do so...

**Comment by hazarkarabay** [comment]
Merged, thank you very much for your contribution.

**Pull request merged**
